version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(levelname)s | %(asctime)s | %(message)s'
    datefmt: '%H:%M'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout

root:
  level: INFO
  handlers:
    - console